### ISSUE TITLE
V2 Support? 👀

### ISSUE THREAD

**Issue by druidOfCode** [softbank-robotics-america/pepper-chat-dialogflow-fulfillment-library#1]
Hey, I was just wondering if this resource would be updated for V2, We use the FirebaseFullfillment code (with some minor edits) for our local Pepper and were hoping that maybe an update would be released over here before the Dialogflow V2 mandate executes ☠️ our Pepper 😬.

(I might also be in the wrong spot though, this is the library referenced in the FAQ's right? https://softbankroboticstraining.github.io/pepper-chatbot-api/#faq-amp-limitations)

**Comment by DanieltheYogi** [comment]
It’s released under the branch dialogflow-v2
